### ISSUE TITLE
context.restore()

### ISSUE THREAD

**Issue by 1j01** [epistemex/8-bit#1]
It's very useful for animating, and other things as well.

This should be pretty simple to implement since the other matrix functionality is already there.

**Comment by epistemex** [comment]
Good news, `restore()` (as well as `save()`) is already in place (https://github.com/epistemex/8-bit/blob/master/src/core.js#L129). Though, IIRC it still is in alpha for some states.

**Comment by 1j01** [comment]
Hm, it doesn't seem be be working for me. [Here's a fiddle.](https://jsfiddle.net/1j01/t00twvu0/) The `ctx.translate` line is supposed to center it, but if you uncomment it, it presumably "shoots off" (It works with `getContext("2d")`)

**Comment by 1j01** [comment]
Or, [simpler example](https://jsfiddle.net/1j01/t00twvu0/1/), just `save`, `translate` and `restore`

**Comment by epistemex** [comment]
@1j01 yeah, as mentioned, it is still in alpha so some states aren't reset fully.

What you can do temporarily to around the problem is to reset the transforms (this is in any case faster than save/restore) using a identity-matrix (`ctx.setTransform(1,0,0,1,0,0)` or `ctx.resetTransform()`), or reverse the last transform f.ex. translate in this case ([example fiddle](https://jsfiddle.net/epistemex/t00twvu0/2/))

**Comment by 1j01** [comment]
Oh, so the `matrix` is just outside of the `State` for now. How big of a change would it be to move it in?
As a quick fix we could push/pop `[state, matrix]` onto/from the stack:
```js
	this.save = function() {
		stack.push([state, matrix]);
		state = new _8bit.State(palette, state);
		return me
	};

	this.restore = function() {
		var s = stack.pop();
		if (s) {
			state = s[0];
			matrix = s[1];
		}
		return me
	};
```

**Comment by epistemex** [comment]
It turns out to be a simple object reference error. Next update will reference `state.matrix` instead of local `matrix` (the matrix object uses properties which are not cross-referenced). The logic of the two methods is otherwise fine.
