### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by 1j01** [epistemex/8-bit#4]
It would be good to have some working examples to check out or start from

**Comment by epistemex** [comment]
Thanks for the interest @1j01 ! True. It's in very early alpha and I am in a startup project so I am uncertain when I will get the time to prioritize this. But, although missing some implementations it's pretty much the same as using the normal 2d context just that the colors depend on a selected palette (custom or predefined). I will try to find time to hack together a starter example to show the main differences shortly.

**Comment by epistemex** [comment]
There will be a simple example (tutorial section in the docs/index.html file) included as a starter. It shows how to use the options as of now, as well as index numbers with colors (turning off strict-mode). It's otherwise similar to 2D context. More details later when the alpha version progresses into beta.

**Comment by 1j01** [comment]
I made the [start of a little drawing app](https://jsfiddle.net/juse2utd/), which could be one of the demos. Also [this thing](https://jsfiddle.net/1wdp7muz/) / [1](https://jsfiddle.net/1wdp7muz/1/).
